const SUBDISTRICTS = {
  'Jakarta': ['Kec. Menteng', 'Kec. Tanah Abang', 'Kec. Kebayoran Baru', 'Kec. Pasar Minggu', 'Kec. Cilincing'],
  'Bandung': ['Kec. Coblong', 'Kec. Sukajadi', 'Kec. Bandung Wetan', 'Kec. Cibeunying Kaler', 'Kec. Bojongloa Kaler'],
  'Surabaya': ['Kec. Tegalsari', 'Kec. Gubeng', 'Kec. Wonokromo', 'Kec. Sukolilo', 'Kec. Rungkut'],
  'Semarang': ['Kec. Semarang Tengah', 'Kec. Semarang Timur', 'Kec. Gajahmungkur', 'Kec. Tembalang', 'Kec. Ngaliyan'],
  'Yogyakarta': ['Kec. Gondomanan', 'Kec. Kotagede', 'Kec. Umbulharjo', 'Kec. Depok', 'Kec. Ngaglik'],
  'Medan': ['Kec. Medan Baru', 'Kec. Medan Polonia', 'Kec. Medan Timur', 'Kec. Medan Tuntungan', 'Kec. Medan Johor'],
  'Palembang': ['Kec. Ilir Timur I', 'Kec. Ilir Barat I', 'Kec. Kemuning', 'Kec. Sukarami', 'Kec. Alang-Alang Lebar'],
  'Makassar': ['Kec. Mariso', 'Kec. Makassar', 'Kec. Panakkukang', 'Kec. Tamalate', 'Kec. Biringkanaya'],
  'Denpasar': ['Kec. Denpasar Barat', 'Kec. Denpasar Timur', 'Kec. Denpasar Selatan', 'Kec. Denpasar Utara', 'Kec. Kuta'],
  'Manado': ['Kec. Wenang', 'Kec. Sario', 'Kec. Malalayang', 'Kec. Mapanget', 'Kec. Bunaken'],
  'Pontianak': ['Kec. Pontianak Kota', 'Kec. Pontianak Utara', 'Kec. Pontianak Timur', 'Kec. Pontianak Selatan', 'Kec. Pontianak Barat'],
  'Balikpapan': ['Kec. Balikpapan Kota', 'Kec. Balikpapan Timur', 'Kec. Balikpapan Utara', 'Kec. Balikpapan Selatan'],
  'Banjarmasin': ['Kec. Banjarmasin Tengah', 'Kec. Banjarmasin Timur', 'Kec. Banjarmasin Selatan', 'Kec. Banjarmasin Utara'],
  'Pekanbaru': ['Kec. Sukajadi', 'Kec. Lima Puluh', 'Kec. Tampan', 'Kec. Marpoyan Damai', 'Kec. Sail'],
  'Batam': ['Kec. Batam Kota', 'Kec. Bengkong', 'Kec. Batu Aji', 'Kec. Nongsa', 'Kec. Sekupang'],
  'Padang': ['Kec. Padang Barat', 'Kec. Padang Timur', 'Kec. Padang Utara', 'Kec. Koto Tangah', 'Kec. Lubuk Begalung'],
  'Bogor': ['Kec. Bogor Tengah', 'Kec. Bogor Utara', 'Kec. Bogor Timur', 'Kec. Bogor Selatan', 'Kec. Tanah Sareal'],
  'Malang': ['Kec. Klojen', 'Kec. Blimbing', 'Kec. Lowokwaru', 'Kec. Kedungkandang', 'Kec. Sukun'],
  'Solo': ['Kec. Laweyan', 'Kec. Serengan', 'Kec. Pasar Kliwon', 'Kec. Jebres', 'Kec. Banjarsari'],
  'Cirebon': ['Kec. Kejaksan', 'Kec. Lemahwungkuk', 'Kec. Pekalipan', 'Kec. Harjamukti', 'Kec. Kesambi'],
  'Banda Aceh': ['Kec. Meuraxa', 'Kec. Kuta Alam', 'Kec. Syiah Kuala', 'Kec. Baiturrahman', 'Kec. Ulee Kareng'],
  'Bandar Lampung': ['Kec. Teluk Betung', 'Kec. Tanjung Karang', 'Kec. Kedaton', 'Kec. Kemiling', 'Kec. Sukabumi'],
  'Samarinda': ['Kec. Samarinda Ulu', 'Kec. Samarinda Ilir', 'Kec. Sungai Kunjang', 'Kec. Loa Janan', 'Kec. Sambutan'],
  'Tangerang': ['Kec. Ciledug', 'Kec. Cipondoh', 'Kec. Karawaci', 'Kec. Tangerang', 'Kec. Pinang'],
  'Bekasi': ['Kec. Bekasi Timur', 'Kec. Bekasi Barat', 'Kec. Bekasi Utara', 'Kec. Bekasi Selatan', 'Kec. Rawalumbu'],
  'Depok': ['Kec. Pancoran Mas', 'Kec. Cimanggis', 'Kec. Sawangan', 'Kec. Sukmajaya', 'Kec. Beji'],
  'Jayapura': ['Kec. Jayapura Utara', 'Kec. Jayapura Selatan', 'Kec. Abepura', 'Kec. Heram', 'Kec. Muara Tami'],
  'Ambon': ['Kec. Nusaniwe', 'Kec. Sirimau', 'Kec. Teluk Ambon', 'Kec. Baguala', 'Kec. Leitimur Selatan'],
  'Mataram': ['Kec. Mataram', 'Kec. Cakranegara', 'Kec. Selaparang', 'Kec. Sandubaya', 'Kec. Ampenan'],
  'Kupang': ['Kec. Kelapa Lima', 'Kec. Kota Lama', 'Kec. Kota Raja', 'Kec. Maulafa', 'Kec. Alak'],
  'Palu': ['Kec. Palu Timur', 'Kec. Palu Barat', 'Kec. Palu Selatan', 'Kec. Palu Utara', 'Kec. Tatanga'],
  'Kendari': ['Kec. Kendari', 'Kec. Baruga', 'Kec. Mandonga', 'Kec. Puuwatu', 'Kec. Kambu'],
  'Jambi': ['Kec. Jambi Timur', 'Kec. Jambi Selatan', 'Kec. Jelutung', 'Kec. Pasar Jambi', 'Kec. Danau Teluk'],
  'Bengkulu': ['Kec. Gading Cempaka', 'Kec. Kampung Melayu', 'Kec. Ratu Agung', 'Kec. Ratu Samban', 'Kec. Sungai Serut'],
  'Tanjung Pinang': ['Kec. Bukit Bestari', 'Kec. Tanjung Pinang Timur', 'Kec. Tanjung Pinang Barat', 'Kec. Kampung Bugis'],
  'Mamuju': ['Kec. Mamuju', 'Kec. Simboro', 'Kec. Kalukku', 'Kec. Papalang', 'Kec. Tommo'],
  'Gorontalo': ['Kec. Gorontalo', 'Kec. Hulonthalangi', 'Kec. Dumbo Raya', 'Kec. Sipatana', 'Kec. Kota Barat'],
  'Ternate': ['Kec. Ternate Utara', 'Kec. Ternate Selatan', 'Kec. Ternate Tengah', 'Kec. Moti', 'Kec. Pulau Hiri'],
  'Palangkaraya': ['Kec. Pahandut', 'Kec. Bukit Batu', 'Kec. Jekan Raya', 'Kec. Sebangau', 'Kec. Rakumpit'],
  'Manokwari': ['Kec. Manokwari Barat', 'Kec. Manokwari Timur', 'Kec. Manokwari Utara', 'Kec. Manokwari Selatan'],
  'Tanjung Selor': ['Kec. Tanjung Selor', 'Kec. Tanjung Palas', 'Kec. Tanjung Palas Barat', 'Kec. Tanjung Palas Timur'],
  'Pangkal Pinang': ['Kec. Pangkal Pinang', 'Kec. Girimaya', 'Kec. Gerunggang', 'Kec. Rangkui', 'Kec. Taman Sari'],
  'Serang': ['Kec. Serang', 'Kec. Curug', 'Kec. Cipocok Jaya', 'Kec. Taktakan', 'Kec. Kasemen'],
}

export function getSubdistricts(city) {
  return SUBDISTRICTS[city] || ['Kecamatan Lainnya']
}
